# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHt3cm38PtCPuHiubonCojHTeYTcFa5y
"""

print("="*30,"\n   =구구단 출력 프로그램=","\n =by 남해우리(컴퓨터공학과)=\n","="*30)

while True:
  tt=int(input("몇 단을 출력할까요?: "))
  for i in range(1,10):
    print(tt,"x",i,"=",tt*i)
  yn=input("계속하려면 y를 입력하시고 멈추려면 n을 입력하세요.:")
  if yn=="n"or yn=="N"or yn=="ㅜ":
    break